### ISSUE TITLE
Switcam HS-303 - not work netip, onvif, rtsp

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/majestic_issues#8] opened 2021-06-25 05:41 UTC
* Camera board id: Rostelecom Switcam HS-303
 * OpenIPC version: v1.0 OpenWrt based
 * Commit: 8328d61
 * Branch: master

The camera has two interfaces, namely eth0 and wlan0
Work in the local network is always carried out through the wlan0 interface
The video in the browser works fine, thank you

Network problems, maybe it's the same thing, the services are enabled in the config

- no response on netip
- no response on onvif
- no response on rtsp

**Comment by widgetii** [comment] 2021-06-25 08:10
For rtsp issue we have #7 , there is a temporary workaround to fix the issue is to set h264 codec explicitly

**Comment by ZigFisher** [comment] 2021-06-25 08:45
```
eth0      Link encap:Ethernet  HWaddr EC:4C:4D:E7:CD:17  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:1815 (1.7 KiB)
          Interrupt:12 

wlan0     Link encap:Ethernet  HWaddr EC:4C:4D:E7:CD:16  
          inet addr:172.17.32.230  Bcast:172.17.32.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2294 errors:0 dropped:61 overruns:0 frame:0
          TX packets:2291 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:346365 (338.2 KiB)  TX bytes:2094138 (1.9 MiB)
```


```
Fri Jun 25 11:39:36 2021 daemon.info majestic: 11:39:36 INFO  [netip] udp_cb@418: UDP packet received len = 20
Fri Jun 25 11:39:36 2021 daemon.info majestic: 11:39:36 ERROR [netip] reply_discovery@401: NETIP: Discovery reply failed: Network is unreachable
Fri Jun 25 11:39:36 2021 daemon.info majestic: 11:39:36 INFO  [netip] udp_cb@418: UDP packet received len = 20
Fri Jun 25 11:39:36 2021 daemon.info majestic: 11:39:36 ERROR [netip] reply_discovery@401: NETIP: Discovery reply failed: Network is unreachable
Fri Jun 25 11:39:37 2021 daemon.info majestic: 11:39:37 INFO  [netip] udp_cb@418: UDP packet received len = 20
Fri Jun 25 11:39:37 2021 daemon.info majestic: 11:39:37 ERROR [netip] reply_discovery@401: NETIP: Discovery reply failed: Network is unreachable
```

**Comment by ZigFisher** [comment] 2021-06-25 09:00
> For rtsp issue we have #7 , there is a temporary workaround to fix the issue is to set h264 codec explicitly

The RTSP workaround worm is working, tested, thank you !

**Comment by widgetii** [comment] 2021-06-25 13:01
For NETIP and ONVIF it seems fixed in the latest build, please test and close the issue if is ok

**Comment by ZigFisher** [comment] 2021-06-25 20:17
The new version works fine, man !
Thank you very much. The ticket can be closed.

**Closed** 2021-06-25 20:30 UTC
